name: GH-Actions
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always
  RUSTUP_TOOLCHAIN: 1.85.0

jobs:
  rust_service_build:
    runs-on: cronos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true
      - name: Install dependencies
        run: apt-get update && apt-get install -y build-essential pkg-config libssl-dev
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.85.0
          . "$HOME/.cargo/env"
          rustup default 1.85.0
      - name: Build
        run: |
          . "$HOME/.cargo/env"
          cargo build
      - name: Test
        run: |
          . "$HOME/.cargo/env"
          cargo test
      - name: Build Docker image
        run: |
          docker build --no-cache \
            --label git_sha=${{ github.sha }} \
            --label build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --label version=${{ github.ref_name }} \
            --label repository=${{ github.repository }} \
            -t rust-service:${{ github.sha }} \
            .